name: Feature Request
description: "Suggest a feature or idea to Rancher Desktop."
labels: ["kind/enhancement"]
body:
- type: textarea
  attributes:
    label: Problem Description
    description: "A clear and concise description of what enhancement you'd like."
  validations:
    required: true
- type: textarea
  attributes:
    label: Proposed Solution
    description: "Describe the solution you'd like in a clear and concise manner."
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: "Add any other context/information about the problem here."
  validations:
    required: false
