linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - unnamedResult
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  gomnd:
    # don't include the "operation" and "assign"
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
    ignored-functions:
      - ^strings\.SplitN$
      - ^os\.FileMode$
      - ^os\.Mkdir(?:All)?$
  lll:
    line-length: 140
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - goconst
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - ineffassign
    - misspell
    - typecheck
    - unconvert
    - unused
    - whitespace
issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic
    - # Exclude bodyclose when it's passed to client.ProcessRequestForAPI
      # or client.ProcessRequestForUtility which internally closes the body.
      path: src/go/rdctl/
      linters: [ bodyclose ]
      source: "client.ProcessRequestFor(API|Utility)\\(rdClient.DoRequest(WithPayload)?\\("
    - # Exclude ST1005 when it encounters errors starting with proper noun
      linters: [ stylecheck ]
      text: "ST1005:"
      path: src/go/wsl-helper/cmd/kubeconfig.go
      source: errors.New\("Windows
    - # Exclude long function declarations
      linters: [ lll ]
      source: ^\s*func\b
    - # Exclude the FIXME comments from upstream
      path: src/go/wsl-helper/pkg/dockerproxy/platform/vsock_linux\.go
      linters: [ gocritic ]
      text: todoCommentWithoutDetail
    - # Ignore errors from syscall
      linters: [ dogsled ]
      source: ^\s*_, _, _ = .*\.Call\(
